CREATE OR REPLACE VIEW CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.V_NON_PIVOT AS 
SELECT 
    BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 'LAG1' AS LAG, 
    CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
    SUM(STAT) AS STAT,
    SUM(AERA) AS AERA,
    SUM(UCFC) AS UCFC,
    SUM(CFC) AS CFC,
    SUM(MVF) AS MVF,
    SUM(SAF) AS SAF,
    SUM(BOP) AS BOP,
    SUM(OIF) AS OIF,
    SUM(SALE) AS SALE,
    SUM(SADJ) AS SADJ
FROM (
    SELECT DISTINCT
        BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 
        CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
        CASE WHEN FORECAST_TYPE = 'STAT' THEN LAG1 END AS STAT,
        CASE WHEN FORECAST_TYPE = 'AERA' THEN LAG1 END AS AERA,
        CASE WHEN FORECAST_TYPE = 'UFC' THEN LAG1 END AS UCFC,
        CASE WHEN FORECAST_TYPE = 'CFC' THEN LAG1 END AS CFC,
        CASE WHEN FORECAST_TYPE = 'MVF' THEN LAG1 END AS MVF,
        CASE WHEN FORECAST_TYPE = 'SAF' THEN LAG1 END AS SAF,
        CASE WHEN FORECAST_TYPE = 'BOP' THEN LAG1 END AS BOP,
        CASE WHEN FORECAST_TYPE = 'OIF' THEN LAG1 END AS OIF,
        CASE WHEN FORECAST_TYPE = 'SALE' THEN LAG1 END AS SALE,
        CASE WHEN FORECAST_TYPE = 'SADJ' THEN LAG1 END AS SADJ
    FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
) AS LAG1_DATA
GROUP BY ALL

UNION ALL 

SELECT 
    BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 'LAG2' AS LAG, 
    CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
    SUM(STAT) AS STAT,
    SUM(AERA) AS AERA,
    SUM(UCFC) AS UCFC,
    SUM(CFC) AS CFC,
    SUM(MVF) AS MVF,
    SUM(SAF) AS SAF,
    SUM(BOP) AS BOP,
    SUM(OIF) AS OIF,
    SUM(SALE) AS SALE,
    SUM(SADJ) AS SADJ
FROM (
    SELECT DISTINCT
        BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 
        CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
        CASE WHEN FORECAST_TYPE = 'STAT' THEN LAG2 END AS STAT,
        CASE WHEN FORECAST_TYPE = 'AERA' THEN LAG2 END AS AERA,
        CASE WHEN FORECAST_TYPE = 'UFC' THEN LAG2 END AS UCFC,
        CASE WHEN FORECAST_TYPE = 'CFC' THEN LAG2 END AS CFC,
        CASE WHEN FORECAST_TYPE = 'MVF' THEN LAG2 END AS MVF,
        CASE WHEN FORECAST_TYPE = 'SAF' THEN LAG2 END AS SAF,
        CASE WHEN FORECAST_TYPE = 'BOP' THEN LAG2 END AS BOP,
        CASE WHEN FORECAST_TYPE = 'OIF' THEN LAG2 END AS OIF,
        CASE WHEN FORECAST_TYPE = 'SALE' THEN LAG2 END AS SALE,
        CASE WHEN FORECAST_TYPE = 'SADJ' THEN LAG2 END AS SADJ
    FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
) AS LAG2_DATA
GROUP BY ALL

UNION ALL 

SELECT 
    BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 'LAG3' AS LAG, 
    CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
    SUM(STAT) AS STAT,
    SUM(AERA) AS AERA,
    SUM(UCFC) AS UCFC,
    SUM(CFC) AS CFC,
    SUM(MVF) AS MVF,
    SUM(SAF) AS SAF,
    SUM(BOP) AS BOP,
    SUM(OIF) AS OIF,
    SUM(SALE) AS SALE,
    SUM(SADJ) AS SADJ
FROM (
    SELECT DISTINCT
        BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 
        CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
        CASE WHEN FORECAST_TYPE = 'STAT' THEN LAG3 END AS STAT,
        CASE WHEN FORECAST_TYPE = 'AERA' THEN LAG3 END AS AERA,
        CASE WHEN FORECAST_TYPE = 'UFC' THEN LAG3 END AS UCFC,
        CASE WHEN FORECAST_TYPE = 'CFC' THEN LAG3 END AS CFC,
        CASE WHEN FORECAST_TYPE = 'MVF' THEN LAG3 END AS MVF,
        CASE WHEN FORECAST_TYPE = 'SAF' THEN LAG3 END AS SAF,
        CASE WHEN FORECAST_TYPE = 'BOP' THEN LAG3 END AS BOP,
        CASE WHEN FORECAST_TYPE = 'OIF' THEN LAG3 END AS OIF,
        CASE WHEN FORECAST_TYPE = 'SALE' THEN LAG3 END AS SALE,
        CASE WHEN FORECAST_TYPE = 'SADJ' THEN LAG3 END AS SADJ
    FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
) AS LAG3_DATA
GROUP BY ALL

UNION ALL 

SELECT 
    BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 'LAG4' AS LAG, 
    CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
    SUM(STAT) AS STAT,
    SUM(AERA) AS AERA,
    SUM(UCFC) AS UCFC,
    SUM(CFC) AS CFC,
    SUM(MVF) AS MVF,
    SUM(SAF) AS SAF,
    SUM(BOP) AS BOP,
    SUM(OIF) AS OIF,
    SUM(SALE) AS SALE,
    SUM(SADJ) AS SADJ
FROM (
    SELECT DISTINCT
        BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 
        CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
        CASE WHEN FORECAST_TYPE = 'STAT' THEN LAG4 END AS STAT,
        CASE WHEN FORECAST_TYPE = 'AERA' THEN LAG4 END AS AERA,
        CASE WHEN FORECAST_TYPE = 'UFC' THEN LAG4 END AS UCFC,
        CASE WHEN FORECAST_TYPE = 'CFC' THEN LAG4 END AS CFC,
        CASE WHEN FORECAST_TYPE = 'MVF' THEN LAG4 END AS MVF,
        CASE WHEN FORECAST_TYPE = 'SAF' THEN LAG4 END AS SAF,
        CASE WHEN FORECAST_TYPE = 'BOP' THEN LAG4 END AS BOP,
        CASE WHEN FORECAST_TYPE = 'OIF' THEN LAG4 END AS OIF,
        CASE WHEN FORECAST_TYPE = 'SALE' THEN LAG4 END AS SALE,
        CASE WHEN FORECAST_TYPE = 'SADJ' THEN LAG4 END AS SADJ
    FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
) AS LAG4_DATA
GROUP BY ALL 
    
UNION ALL 

SELECT 
    BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 'LAG5' AS LAG, 
    CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
    SUM(STAT) AS STAT,
    SUM(AERA) AS AERA,
    SUM(UCFC) AS UCFC,
    SUM(CFC) AS CFC,
    SUM(MVF) AS MVF,
    SUM(SAF) AS SAF,
    SUM(BOP) AS BOP,
    SUM(OIF) AS OIF,
    SUM(SALE) AS SALE,
    SUM(SADJ) AS SADJ
FROM (
    SELECT DISTINCT
        BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 
        CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
        CASE WHEN FORECAST_TYPE = 'STAT' THEN LAG5 END AS STAT,
        CASE WHEN FORECAST_TYPE = 'AERA' THEN LAG5 END AS AERA,
        CASE WHEN FORECAST_TYPE = 'UFC' THEN LAG5 END AS UCFC,
        CASE WHEN FORECAST_TYPE = 'CFC' THEN LAG5 END AS CFC,
        CASE WHEN FORECAST_TYPE = 'MVF' THEN LAG5 END AS MVF,
        CASE WHEN FORECAST_TYPE = 'SAF' THEN LAG5 END AS SAF,
        CASE WHEN FORECAST_TYPE = 'BOP' THEN LAG5 END AS BOP,
        CASE WHEN FORECAST_TYPE = 'OIF' THEN LAG5 END AS OIF,
        CASE WHEN FORECAST_TYPE = 'SALE' THEN LAG5 END AS SALE,
        CASE WHEN FORECAST_TYPE = 'SADJ' THEN LAG5 END AS SADJ
    FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
) AS LAG5_DATA
GROUP BY ALL

UNION ALL 

SELECT 
    BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 'LAG6' AS LAG, 
    CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
    SUM(STAT) AS STAT,
    SUM(AERA) AS AERA,
    SUM(UCFC) AS UCFC,
    SUM(CFC) AS CFC,
    SUM(MVF) AS MVF,
    SUM(SAF) AS SAF,
    SUM(BOP) AS BOP,
    SUM(OIF) AS OIF,
    SUM(SALE) AS SALE,
    SUM(SADJ) AS SADJ
FROM (
    SELECT DISTINCT
        BU, MATERIAL_NUMBER, PLANT, SHIPTO, SOLDTO, SUPERREGION, SALES_ORG, PRODUCT_GROUPCODE, GLOBAL_GRADE, 
        CALENDAR_YEAR_AND_MONTH, TIME_PERIOD, 
        CASE WHEN FORECAST_TYPE = 'STAT' THEN LAG6 END AS STAT,
        CASE WHEN FORECAST_TYPE = 'AERA' THEN LAG6 END AS AERA,
        CASE WHEN FORECAST_TYPE = 'UFC' THEN LAG6 END AS UCFC,
        CASE WHEN FORECAST_TYPE = 'CFC' THEN LAG6 END AS CFC,
        CASE WHEN FORECAST_TYPE = 'MVF' THEN LAG6 END AS MVF,
        CASE WHEN FORECAST_TYPE = 'SAF' THEN LAG6 END AS SAF,
        CASE WHEN FORECAST_TYPE = 'BOP' THEN LAG6 END AS BOP,
        CASE WHEN FORECAST_TYPE = 'OIF' THEN LAG6 END AS OIF,
        CASE WHEN FORECAST_TYPE = 'SALE' THEN LAG6 END AS SALE,
        CASE WHEN FORECAST_TYPE = 'SADJ' THEN LAG6 END AS SADJ
    FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
) AS LAG6_DATA
GROUP BY ALL;