CREATE OR REPLACE VIEW CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.V_PIVOT(
	BU,
	MATERIAL_NUMBER,
	PLANT,
	SHIPTO,
	SOLDTO,
	SUPERREGION,
	SALES_ORG,
	PRODUCT_GROUPCODE,
	GLOBAL_GRADE,
	LAG,
	CALENDAR_YEAR_AND_MONTH,
	TIME_PERIOD,
	STAT,
	AERA,
	UCFC,
	CFC,
	MVF,
	SAF,
	BOP,
	OIF,
	SALE,
	SADJ
) as(SELECT * FROM (
  SELECT DISTINCT BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,FORECAST_TYPE,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,'LAG1' AS A,
  CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,LAG1 FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
  WHERE FORECAST_TYPE IN ('STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ') 
) LAG
PIVOT (
  SUM(LAG1)
  FOR FORECAST_TYPE
  IN (
    'STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ'
  )
)as P(BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,LAG,CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,
STAT,AERA,UCFC,CFC,MVF,SAF,BOP,OIF,SALE,SADJ)

UNION ALL
SELECT * FROM (
  SELECT DISTINCT BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,FORECAST_TYPE,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,'LAG2' AS A,
  CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,LAG2 FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
  WHERE FORECAST_TYPE IN ('STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ') 
) LAG
PIVOT (
  SUM(LAG2)
  FOR FORECAST_TYPE
  IN (
    'STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ'
  )
)as P(BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,LAG,CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,
STAT,AERA,UCFC,CFC,MVF,SAF,BOP,OIF,SALE,SADJ)

UNION ALL
SELECT * FROM (
  SELECT DISTINCT BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,FORECAST_TYPE,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,'LAG3' AS A,
  CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,LAG3 FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
  WHERE FORECAST_TYPE IN ('STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ') 
) LAG
PIVOT (
  SUM(LAG3)
  FOR FORECAST_TYPE
  IN (
    'STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ'
  )
)as P(BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,LAG,CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,
STAT,AERA,UCFC,CFC,MVF,SAF,BOP,OIF,SALE,SADJ)
UNION ALL
SELECT * FROM (
  SELECT DISTINCT BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,FORECAST_TYPE,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,'LAG4' AS A,
  CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,LAG4 FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
  WHERE FORECAST_TYPE IN ('STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ') 
) LAG
PIVOT (
  SUM(LAG4)
  FOR FORECAST_TYPE
  IN (
    'STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ'
  )
)as P(BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,LAG,CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,
STAT,AERA,UCFC,CFC,MVF,SAF,BOP,OIF,SALE,SADJ)
UNION ALL
SELECT * FROM (
  SELECT DISTINCT BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,FORECAST_TYPE,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,'LAG5' AS A,
  CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,LAG5 FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
  WHERE FORECAST_TYPE IN ('STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ') 
) LAG
PIVOT (
  SUM(LAG5)
  FOR FORECAST_TYPE
  IN (
    'STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ'
  )
)as P(BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,LAG,CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,STAT,AERA,UCFC,CFC,SAF,BOP,OIF,SALE,SADJ)
UNION ALL SELECT * FROM (
  SELECT DISTINCT BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,FORECAST_TYPE,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,'LAG6' AS A,
  CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,LAG6 FROM CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.VW_SOURCE
  WHERE FORECAST_TYPE IN ('STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ') 
) LAG
PIVOT (
  SUM(LAG6)
  FOR FORECAST_TYPE
  IN (
    'STAT','AERA','UFC','CFC','MVF','SAF','BOP','OIF','SALE','SADJ'
  )
)as P(BU,MATERIAL_NUMBER,PLANT,SHIPTO,SOLDTO,SUPERREGION,SALES_ORG,PRODUCT_GROUPCODE,GLOBAL_GRADE,LAG,CALENDAR_YEAR_AND_MONTH,TIME_PERIOD,
STAT,AERA,UCFC,CFC,MVF,SAF,BOP,OIF,SALE,SADJ));
